apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: nodejs
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: nodejs
  selector:
    app: nodejs
