{{- range cluster1 }}
{{- if true }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-%s" .name "nodejs"}}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nodejs-chart
    repoURL: 'https://github.com/agarwalhardik/argocd-demo.git'
    targetRevision: 'HEAD'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
---
{{- end }}