apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: nginx
  selector:
    app: nginx
